name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 1.1.0
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0
  meta: ^1.1.7
  csv: ^4.0.3
  recase: ^2.0.1 
  code_builder: ^3.2.0
  dart_style: ^1.2.7 
  source_gen: ^0.9.0
  flutter_sheet_localization: ^1.0.0
  build: ^1.2.0
  analyzer: ^0.37.0
  collection: ^1.14.11

dev_dependencies:
  build_test: ^0.10.3
  build_runner: ^1.0.0